@startuml
'''classes
class Labyrinthe{
  +pj : Perso
  +murs : boolean[][]
  {static}getSuivant(int x, int y, String action)
  +Labyrinthe(String nom)
  +deplacerPerso(String action)
  +etreFini()
  +getLenghtY()
  +getLenght()
  +getMur()
}

class Perso{
  x:int
  y:int
  +Perso(int dx, int dy)
  +etrePresent(int dx, int dy)
  +getX()
  +getY()
}

Labyrinthe --> Perso
@enduml